# Generated by Django 3.2.7 on 2021-09-10 07:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBaseMode',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ContentPageModel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Content page',
                'verbose_name_plural': 'Content pages',
            },
        ),
        migrations.CreateModel(
            name='ContentAudioModel',
            fields=[
                ('contentbasemode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.contentbasemode')),
                ('bitrate', models.IntegerField(default=None, null=True, verbose_name='Bitrate')),
            ],
            options={
                'verbose_name': 'Content audio',
                'verbose_name_plural': 'Content audios',
            },
            bases=('content.contentbasemode',),
        ),
        migrations.CreateModel(
            name='ContentTextModel',
            fields=[
                ('contentbasemode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.contentbasemode')),
                ('text', models.TextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Content text',
                'verbose_name_plural': 'Content texts',
            },
            bases=('content.contentbasemode',),
        ),
        migrations.CreateModel(
            name='ContentVideoModel',
            fields=[
                ('contentbasemode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.contentbasemode')),
                ('url_video', models.URLField(blank=True, verbose_name='Video URL')),
                ('url_subtitles', models.URLField(blank=True, verbose_name='Subtitles URL')),
            ],
            options={
                'verbose_name': 'Content video',
                'verbose_name_plural': 'Content videos',
            },
            bases=('content.contentbasemode',),
        ),
        migrations.AddField(
            model_name='contentbasemode',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content', to='content.contentpagemodel', verbose_name='Page'),
        ),
    ]
