# Generated by Django 3.2.7 on 2021-09-09 14:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPageModel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentVideoModel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
                ('url_video', models.URLField(blank=True, verbose_name='Video URL')),
                ('url_subtitles', models.URLField(blank=True, verbose_name='Subtitles URL')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video', to='content.contentpagemodel', verbose_name='Page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentTextModel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
                ('text', models.TextField(verbose_name='Text')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='text', to='content.contentpagemodel', verbose_name='Page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentAudioModel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
                ('bitrate', models.IntegerField(default=None, null=True, verbose_name='Counter')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audio', to='content.contentpagemodel', verbose_name='Page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
