# Generated by Django 3.2.7 on 2021-09-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentaudiomodel',
            name='bitrate',
            field=models.IntegerField(default=None, null=True, verbose_name='Bitrate'),
        ),
    ]
